### PR TITLE
resources: smoother audio recording permission (fixes #5789)

### LINKED ISSUE #5789: crash in pdf reader
FATAL EXCEPTION: main (Ask Gemini)
                                                                                                    Process: org.ole.planet.myplanet, PID: 20228
                                                                                                    java.lang.RuntimeException: setAudioSource failed.
                                                                                                    	at android.media.MediaRecorder.setAudioSource(Native Method)
                                                                                                    	at org.ole.planet.myplanet.service.AudioRecorderService.startRecording(AudioRecorderService.kt:42)
                                                                                                    	at org.ole.planet.myplanet.ui.viewer.PDFReaderActivity.onCreate$lambda$0(PDFReaderActivity.kt:48)
                                                                                                    	at org.ole.planet.myplanet.ui.viewer.PDFReaderActivity.$r8$lambda$2Rh9eYw27cw0eFU-_uWWcGjAhZA(Unknown Source:0)
                                                                                                    	at org.ole.planet.myplanet.ui.viewer.PDFReaderActivity$$ExternalSyntheticLambda0.onClick(D8$$SyntheticClass:0)
                                                                                                    	at android.view.View.performClick(View.java:8028)
                                                                                                    	at android.view.View.performClickInternal(View.java:8005)
                                                                                                    	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
                                                                                                    	at android.view.View$PerformClick.run(View.java:31229)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8705)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

### PR DESCRIPTION
**Pull request by pavi38**
fixes #5789 

https://github.com/user-attachments/assets/2de3317c-4a4e-4a2f-b78d-98f467096291

### CODE REVIEW

File: app/src/main/java/org/ole/planet/myplanet/service/AudioRecorderPermission.kt [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+        }
+    }
+    private fun toggleRecording() {
+        if (recorder?.isRecording()!!) {
+            recorder.stopRecording()
+        } else {
+            recorder.startRecording()
+        }
+    }
+}
```
Comment (Okuro3499) [inline app/src/main/java/org/ole/planet/myplanet/service/AudioRecorderPermission.kt:63]: does this have to be a class? looks like something that could be a function

**Review by Okuro3499 — APPROVED** [review]

**Comment by Okuro3499** [comment]
@pavi38 resolve conflicts

**Review by Avinash-Codes — APPROVED** [review]

**Review by dogi — APPROVED** [review]
