### PR TITLE
login: smoother clearing dialog (fixes #5090)

### LINKED ISSUE #5090: Title: Sync Status Dialog Incorrectly Persists After Clearing App Data
After clearing the app data, the dialog indicating “It has been more than 20109 days since you last synced this device” still appears. This behavior suggests that the app is not properly resetting the sync status or timestamp when app data is cleared. The issue persists even though the data and cache have been wiped, and the app behaves as if old sync data is still present.

Steps to Reproduce:
1. Clear the app data through device settings.

Expected Behavior:
After clearing app data, the app should initialize as a fresh installation without showing outdated sync information.

Potential Cause:
- The sync timestamp or related metadata might be stored in persistent storage (e.g., external storage, Realm database, or shared preferences) that is not cleared along with app data.

https://github.com/user-attachments/assets/765b2718-4355-4aef-80ee-84a701177d58

### PR DESCRIPTION
**Pull request by deeppp15**
## Description

- fixes #5090 
- no of days since last sync are 20116 when we clear data. 
- If no of days are within 356 then show dialog or else do not

## Screenshot

1) Initial Sync 

[initial sync.webm](https://github.com/user-attachments/assets/06f0c40d-5cd6-4735-a076-ac4d223107e9)

2) Clear Data Sync

[clear_data_sync.webm](https://github.com/user-attachments/assets/174b667e-9ffb-4ed3-9bc8-14e860e58887)

### CODE REVIEW

File: app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt [hunk 1]
```diff
@@ -464,12 +465,14 @@ abstract class SyncActivity : ProcessUserDataActivity(), SyncListener, CheckVers
         val msDiff = Calendar.getInstance().timeInMillis - cal_last_Sync.timeInMillis
         val daysDiff = TimeUnit.MILLISECONDS.toDays(msDiff)
         return if (daysDiff >= maxDays) {
-            val alertDialogBuilder = AlertDialog.Builder(this, R.style.AlertDialogTheme)
-            alertDialogBuilder.setMessage("${getString(R.string.it_has_been_more_than)}${(daysDiff - 1)}${getString(R.string.days_since_you_last_synced_this_device)}${getString(R.string.connect_it_to_the_server_over_wifi_and_sync_it_to_reactivate_this_tablet)}")
-            alertDialogBuilder.setPositiveButton(R.string.okay) { _: DialogInterface?, _: Int ->
-                Toast.makeText(applicationContext, getString(R.string.connect_to_the_server_over_wifi_and_sync_your_device_to_continue), Toast.LENGTH_LONG).show()
+            if(daysDiff <= maxDaysPopup){
```
Comment (Okuro3499) [inline app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt:468]: won't this change affect the existing functionality and prevent the dialog from ever showing up.
I think maybe just a reconfiguration of the logic below might fix the problem @deeppp15 what do you think about this?
```
cal_today = Calendar.getInstance(Locale.ENGLISH)
cal_last_Sync = Calendar.getInstance(Locale.ENGLISH)
cal_last_Sync.timeInMillis = settings.getLong("LastSync", 0)
cal_today.timeInMillis = Date().time
val msDiff = Calendar.getInstance().timeInMillis - cal_last_Sync.timeInMillis
val daysDiff = TimeUnit.MILLISECONDS.toDays(msDiff)
```

Comment (deeppp15) [reply app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt]: Hi @Okuro3499 , refactored logic please review

**Review by huitk — APPROVED** [review]

**Review by Okuro3499 — APPROVED** [review]

**Review by dogi — APPROVED** [review]
