### PR TITLE
dashboard: smoother profile image capture (fixes #5797)

### LINKED ISSUE #5797: crash in edit profile
FATAL EXCEPTION: main (Ask Gemini)
                                                                                                    Process: org.ole.planet.myplanet, PID: 21848
                                                                                                    java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.android.camera2/com.android.camera.CaptureActivity clip={text/uri-list hasLabel(0) {U(content)}} (has extras) } from ProcessRecord{455eec 21848:org.ole.planet.myplanet/u0a218} (pid=21848, uid=10218) with revoked permission android.permission.CAMERA
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3242)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3226)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3209)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3151)
                                                                                                    	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2069)
                                                                                                    	at android.app.Instrumentation.execStartActivity(Instrumentation.java:2000)
                                                                                                    	at android.app.Activity.startActivityForResult(Activity.java:5874)
                                                                                                    	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:780)
                                                                                                    	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:243)
                                                                                                    	at androidx.activity.ComponentActivity$1.onLaunch(ComponentActivity.java:239)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:173)
                                                                                                    	at androidx.fragment.app.Fragment$10.launch(Fragment.java:3612)
                                                                                                    	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
                                                                                                    	at org.ole.planet.myplanet.ui.userprofile.UserProfileFragment.takePhoto(UserProfileFragment.kt:342)
                                                                                                    	at org.ole.planet.myplanet.ui.userprofile.UserProfileFragment.searchForPhoto$lambda$11(UserProfileFragment.kt:313)
                                                                                                    	at org.ole.planet.myplanet.ui.userprofile.UserProfileFragment.$r8$lambda$CxtQhyv85qgCVHshXgyJ-v3oRaE(Unknown Source:0)
                                                                                                    	at org.ole.planet.myplanet.ui.userprofile.UserProfileFragment$$ExternalSyntheticLambda2.onClick(D8$$SyntheticClass:0)
                                                                                                    	at androidx.appcompat.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1068)
                                                                                                    	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
                                                                                                    	at android.widget.AbsListView.performItemClick(AbsListView.java:1273)
                                                                                                    	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3286)
                                                                                                    	at android.widget.AbsListView.onTouchUp(AbsListView.java:4264)
                                                                                                    	at android.widget.AbsListView.onTouchEvent(AbsListView.java:4005)
                                                                                                    	at android.view.View.performOnTouchCallback(View.java:16447)
                                                                                                    	at android.view.View.dispatchTouchEvent(View.java:16404)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3116)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2789)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
                                                                                                    	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:458)
                                                                                                    	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1980)
                                                                                                    	at android.app.Dialog.dispatchTouchEvent(Dialog.java:935)
                                                                                                    	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
                                                                                                    	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:416)

### PR DESCRIPTION
**Pull request by pavi38**
fixes #5797

### CODE REVIEW

File: app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt [hunk 1]
```diff
@@ -94,6 +98,31 @@ class UserProfileFragment : Fragment() {
...
+                            dialog.dismiss()
+                            val intent = Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS)
+                            val uri: Uri = Uri.fromParts("package", requireContext().packageName, null)
+                            intent.data = uri
+                            startActivity(intent)
+                        }
+                        .setNegativeButton(R.string.cancel) { dialog, _ -> dialog.dismiss() }
+                        .show()
+                } else {
+                    Utilities.toast(requireContext(), "camera permission is required.")
```
Comment (Okuro3499) [inline app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt:122]: instead of the toast can we instead ask the user to allow the permission

**Review by Okuro3499 — CHANGES_REQUESTED** [review]

**Review by Avinash-Codes — CHANGES_REQUESTED** [review]
@pavi38 Agee with @Okuro3499

File: app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt (hunk 1 above)
Comment (pavi38) [reply app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt:122]: hi @Okuro3499 are you talking about showing permission rationale?

File: app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt [hunk 2]
```diff
@@ -94,6 +98,31 @@ class UserProfileFragment : Fragment() {
...
             }
         }
+
+        requestCameraLauncher = registerForActivityResult(
+            ActivityResultContracts.RequestPermission()
+        ) { isGranted ->
+            if (isGranted) {
+                takePhoto()
+            } else {
+                if (!shouldShowRequestPermissionRationale(Manifest.permission.RECORD_AUDIO)) {
```
Comment (Okuro3499) [inline app/src/main/java/org/ole/planet/myplanet/ui/userprofile/UserProfileFragment.kt:108]: also noticed here we are checking if `RECORD_AUDIO` permission was allowed but we require camera permission

**Review by Okuro3499 — CHANGES_REQUESTED** [review]

**Review by Okuro3499 — APPROVED** [review]

**Review by dogi — APPROVED** [review]
