### PR TITLE
all: smoother disclaimer link (fixes #5017)

### LINKED ISSUE #5017: Contact link not working on Disclaimer page
Description:
The Contact link on the Disclaimer page is currently not functioning. When users click on the link, it doesn't redirect to the expected contact page or action, leading to a broken user experience.

Steps to Reproduce:

Navigate to the Disclaimer page in the app.
Locate the Contact link on the page.
Click on the Contact link.
Observe that the link does not work or redirect to the expected contact information or form.
Expected Behavior:
The Contact link should be functional and redirect users to the appropriate contact page or open a dialog for further interaction.

Actual Behavior:
The Contact link does not work and does not redirect the user to the intended location.

### PR DESCRIPTION
**Pull request by Avinash-Codes**
fixes #5017

### CODE REVIEW

**Review by deeppp15 — APPROVED** [review]

File: app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DisclaimerFragment.kt [hunk 1]
```diff
@@ -1,20 +1,38 @@
...
 
 class DisclaimerFragment : Fragment() {
-    private lateinit var fragmentDisclaimerBinding: FragmentDisclaimerBinding
-    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View {
-        fragmentDisclaimerBinding = FragmentDisclaimerBinding.inflate(inflater, container, false)
-        fragmentDisclaimerBinding.tvDisclaimer.text = Html.fromHtml(getString(Constants.DISCLAIMER), HtmlCompat.FROM_HTML_MODE_LEGACY)
-        return fragmentDisclaimerBinding.root
+
+    private var _binding: FragmentDisclaimerBinding? = null
+    private val binding get() = _binding!!
```
Comment (Okuro3499) [inline app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DisclaimerFragment.kt:16]: is it necessary to rename this?

**Review by Okuro3499 — CHANGES_REQUESTED** [review]

**Review by dogi — APPROVED** [review]
