### PR TITLE
enterprises: smoother finances handling (fixes #13072) 

### LINKED ISSUE #13072: Finances section text not visible in dark mode
When switching to dark mode, the text in the 'Finances' section of the enterprises page becomes difficult or impossible to see. This reduces readability and can cause confusion for users trying to view financial information.

**Steps to reproduce:**
1. Navigate to the enterprise's 'Finances' section in MyPlanet.
2. Enable dark mode.
3. Observe that various text elements blend into the background or are not visible.

**Expected behavior:**
All text in the 'Finances' section should remain clearly visible and legible in both light and dark modes.

**Environment:**
- Platform: MyPlanet web
- Theme: Dark Mode

Please adjust the text styling or background in the Finances section to ensure proper visibility in dark mode.

### PR DESCRIPTION
**Pull request by Valerie923**
Screenshot_20260427_230125_org_ole_planet_myplanet_DashboardActivity
Screenshot_20260427_230917

### CODE REVIEW

File: app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterprisesFinancesAdapter.kt [hunk 1]
```diff
@@ -36,10 +36,11 @@ class EnterprisesFinancesAdapter(
     override fun onBindViewHolder(holder: FinanceViewHolder, position: Int) {
         val item = getItem(position)
         val binding = holder.binding
+        val textColor = ContextCompat.getColor(context, R.color.daynight_textColor)
         binding.date.text = item.date?.let { formatDate(it, "MMM dd, yyyy") } ?: ""
         binding.note.text = item.description
-        binding.debit.setTextColor(Color.BLACK)
-        binding.credit.setTextColor(Color.BLACK)
+        binding.debit.setTextColor(textColor)
+        binding.credit.setTextColor(textColor)
```
Comment (Okuro3499) [inline app/src/main/java/org/ole/planet/myplanet/ui/enterprises/EnterprisesFinancesAdapter.kt]: I think these changes would look cleaner if done in the xml file

**Review by Okuro3499 — CHANGES_REQUESTED** [review]

**Comment by Valerie923** [comment]
I have edited the code
Screenshot_20260428_213133_org_ole_planet_myplanet_DashboardActivity (1)

**Review by Okuro3499 — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Comment by Valerie923** [comment]
fixes #13072
