### PR TITLE
teams: smoother tasks assigning (fixes #4787)

### LINKED ISSUE #4787: teams: task assign crash
## Description

- In teams if no members are present (excluding leader) , when created a task and trying to assign a new task.
- Spinner object returns null
- App crashes since it tries to cast null to RealUserModel

## Logs

2024-11-20 14:18:27.219  6413-6413  AndroidRuntime          org.ole.planet.myplanet              E  FATAL EXCEPTION: main
                                                                                                    Process: org.ole.planet.myplanet, PID: 6413
                                                                                                    java.lang.NullPointerException: null cannot be cast to non-null type org.ole.planet.myplanet.model.RealmUserModel
                                                                                                    	at org.ole.planet.myplanet.ui.team.teamTask.TeamTaskFragment.onClickMore$lambda$11(TeamTaskFragment.kt:271)
                                                                                                    	at org.ole.planet.myplanet.ui.team.teamTask.TeamTaskFragment.$r8$lambda$Qk9CTGfNm6Vv_hgKhVpNiQ_qqos(Unknown Source:0)
                                                                                                    	at org.ole.planet.myplanet.ui.team.teamTask.TeamTaskFragment$$ExternalSyntheticLambda0.onClick(D8$$SyntheticClass:0)
                                                                                                    	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7656)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2024-11-20 14:18:27.220  6413-6413  System.err              org.ole.planet.myplanet              W  java.lang.NullPointerException: null cannot be cast to non-null type org.ole.planet.myplanet.model.RealmUserModel
2024-11-20 14:18:27.220  6413-6413  System.err              org.ole.planet.myplanet              W  	at org.ole.planet.myplanet.ui.team.teamTask.TeamTaskFragment.onClickMore$lambda$11(TeamTaskFragment.kt:271)
2024-11-20 14:18:27.221  6413-6413  System.err              org.ole.planet.myplanet              W  	at org.ole.planet.myplanet.ui.team.teamTask.TeamTaskFragment.$r8$lambda$Qk9CTGfNm6Vv_hgKhVpNiQ_qqos(Unknown Source:0)
2024-11-20 14:18:27.221  6413-6413  System.err              org.ole.planet.myplanet              W  	at org.ole.planet.myplanet.ui.team.teamTask.TeamTaskFragment$$ExternalSyntheticLambda0.onClick(D8$$SyntheticClass:0)
2024-11-20 14:18:27.222  6413-6413  System.err              org.ole.planet.myplanet              W  	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
2024-11-20 14:18:27.222  6413-6413  System.err              org.ole.planet.myplanet              W  	at android.os.Handler.dispatchMessage(Handler.java:106)
2024-11-20 14:18:27.222  6413-6413  System.err              org.ole.planet.myplanet              W  	at android.os.Looper.loop(Looper.java:223)
2024-11-20 14:18:27.222  6413-6413  System.err              org.ole.planet.myplanet              W  	at android.app.ActivityThread.main(ActivityThread.java:7656)
2024-11-20 14:18:27.222  6413-6413  System.err              org.ole.planet.myplanet              W  	at java.lang.reflect.Method.invoke(Native Method)
2024-11-20 14:18:27.222  6413-6413  System.err              org.ole.planet.myplanet              W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
2024-11-20 14:18:27.222  6413-6413  System.err              org.ole.planet.myplanet              W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2024-11-20 14:18:32.767  6413-6423  planet.myplane          org.ole.planet.myplanet              I  Thread[5,tid=6423,WaitingInMainSignalCatcherLoop,Thread*=0xdd346210,peer=0x13880000,"Signal Catcher"]: reacting to signal 3
2024-11-20 14:18:

### PR DESCRIPTION
**Pull request by deeppp15**
## Description

- fixes #4787
- Added checks if the team has no members

## Testing 
- create new teams and assign tasks.

## Screenshots
[No team members to assign task.webm](https://github.com/user-attachments/assets/f492febc-cd85-4824-9e74-62868cf7fcde)

### CODE REVIEW

File: app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt [hunk 1]
```diff
@@ -254,13 +255,22 @@ class TeamTaskFragment : BaseTeamFragment(), OnCompletedListener {
         val alertUsersSpinnerBinding = AlertUsersSpinnerBinding.inflate(LayoutInflater.from(requireActivity()))
         val userList: List<RealmUserModel> = getJoinedMember(teamId, mRealm)
         val filteredUserList = userList.filter { user -> user.getFullName().isNotBlank() }
+        if (filteredUserList.isEmpty()) {
+            Toast.makeText(context, "No Team members present to assign tasks", Toast.LENGTH_SHORT).show()
```
Comment (Okuro3499) [inline app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt:259]: translate these strings

File: app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt [hunk 2]
```diff
@@ -254,13 +255,22 @@ class TeamTaskFragment : BaseTeamFragment(), OnCompletedListener {
...
         val adapter: ArrayAdapter<RealmUserModel> = UserListArrayAdapter(requireActivity(), android.R.layout.simple_list_item_1, filteredUserList)
         alertUsersSpinnerBinding.spnUser.adapter = adapter
         AlertDialog.Builder(requireActivity(), R.style.AlertDialogTheme)
             .setTitle(R.string.select_member)
             .setView(alertUsersSpinnerBinding.root).setCancelable(false)
             .setPositiveButton(R.string.ok) { _: DialogInterface?, _: Int ->
-                val user = alertUsersSpinnerBinding.spnUser.selectedItem as RealmUserModel
+                val selectedItem = alertUsersSpinnerBinding.spnUser.selectedItem
+                if (selectedItem == null) {
+                    Toast.makeText(context, "No member selected. Please try again.", Toast.LENGTH_SHORT).show()
```
Comment (Okuro3499) [inline app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt:270]: this one too

**Review by Okuro3499 — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt (hunk 1 above)
Comment (deeppp15) [reply app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt]: Updated translations please check @Okuro3499

**Review by Okuro3499 — APPROVED** [review]

**Review by Kuljeet1998 — APPROVED** [review]

**Review by dogi — APPROVED** [review]
