### PR TITLE
all: smoother notification navigation (fixes #4883)

### LINKED ISSUE #4883: [Bug] Screen replication issue in notification section
Description:
When navigating to the notification section, if the notification icon is pressed multiple times, the app creates multiple instances of the same screen. Consequently, the user needs to press the back button an equivalent number of times to return to the previous screen.

Steps to Reproduce:

Navigate to the notification section.
Tap the notification icon multiple times.
Observe that the screen seems to replicate multiple times.
Press the back button repeatedly to verify the issue.
Expected Behavior:
Pressing the notification icon multiple times should not replicate the screen. Ideally, the app should either ignore subsequent taps or navigate correctly without duplicating the screen.

Actual Behavior:
The app creates multiple instances of the same screen, requiring several back presses to return to the previous screen.

Screenshots/Video

[Screen_recording_20241216_221806.webm](https://github.com/user-attachments/assets/868cf12e-cf3c-475a-a1cb-0299387ca804)

### PR DESCRIPTION
**Pull request by Avinash-Codes**
fixes #4883

### CODE REVIEW

File: app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt [hunk 1]
```diff
@@ -240,5 +282,6 @@ abstract class DashboardElementActivity : SyncActivity(), FragmentManager.OnBack
         b.putString("type", "enterprise")
         fragment.arguments = b
         openCallFragment(fragment, "Enterprise")
+        Log.d("openEnterpriseFragment", "Opening Enterprise Fragment")
```
Comment (Okuro3499) [inline app/src/main/java/org/ole/planet/myplanet/ui/sync/DashboardElementActivity.kt:285]: remove the logs

**Review by Okuro3499 — CHANGES_REQUESTED** [review]

**Review by Okuro3499 — APPROVED** [review]

**Review by deeppp15 — APPROVED** [review]

**Review by dogi — APPROVED** [review]
