### PR TITLE
sync: trim lite version (fixes #3656)

### LINKED ISSUE #3656: NumberFormatException
```
Exception java.lang.NumberFormatException: For input string: "95-lite"
  at java.lang.Integer.parseInt (Integer.java:747)
  at java.lang.Integer.parseInt (Integer.java:865)
  at org.ole.planet.myplanet.datamanager.Service.compareVersions (Service.kt:360)
  at org.ole.planet.myplanet.datamanager.Service.isVersionAllowed (Service.kt:356)
  at org.ole.planet.myplanet.datamanager.Service.access$isVersionAllowed (Service.kt:39)
  at org.ole.planet.myplanet.datamanager.Service$getMinApk$1.onResponse (Service.kt:300)
  at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$retrofit2-DefaultCallAdapterFactory$ExecutorCallbackCall$1 (DefaultCallAdapterFactory.java:89)
  at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$ExternalSyntheticLambda0.run (D8$$SyntheticClass)
  at android.os.Handler.handleCallback (Handler.java:942)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:201)
  at android.os.Looper.loop (Looper.java:288)
  at android.app.ActivityThread.main (ActivityThread.java:7918)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:936)
```

### PR DESCRIPTION
**Pull request by Okuro3499**
fixes #3656

### CODE REVIEW

File: app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt [hunk 1]
```diff
@@ -295,9 +295,10 @@ class Service(private val context: Context) {
             override fun onResponse(call: Call<JsonObject?>, response: Response<JsonObject?>) {
                 if (response.isSuccessful) {
                     response.body()?.let { jsonObject ->
-                        val currentVersion = "${context.resources.getText(R.string.app_version)}"
+                        val rawCurrentVersion = "${context.resources.getText(R.string.app_version)}"
+                        val cleanCurrentVersion = rawCurrentVersion.replace("-lite", "")
                         val minApkVersion = jsonObject.get("minapk").asString
-                        if (isVersionAllowed(currentVersion, minApkVersion)) {
+                        if (isVersionAllowed(cleanCurrentVersion, minApkVersion)) {
```
Comment (xyb994) [inline app/src/main/java/org/ole/planet/myplanet/datamanager/Service.kt:301]: Since the root of the issue is calling `isVersionAllowed`, which calls `compareVersions`, would it make more sense to make changes in `compareVersions`? There's already `removePrefix("v")`, so we can just add `.removeSuffix("-lite")` behind it?

**Review by xyb994 — APPROVED** [review]

**Review by dogi — APPROVED** [review]
