### PR TITLE
resources: smoother recording audio permissions (fixes #5702)

### LINKED ISSUE #5702: crash while creating a audio resource
FATAL EXCEPTION: main (Ask Gemini)
                                                                                                    Process: org.ole.planet.myplanet, PID: 20213
                                                                                                    java.lang.RuntimeException: setAudioSource failed.
                                                                                                    	at android.media.MediaRecorder.setAudioSource(Native Method)
                                                                                                    	at org.ole.planet.myplanet.service.AudioRecorderService.startRecording(AudioRecorderService.kt:42)
                                                                                                    	at org.ole.planet.myplanet.ui.resources.AddResourceFragment.showAudioRecordAlert$lambda$10(AddResourceFragment.kt:135)
                                                                                                    	at org.ole.planet.myplanet.ui.resources.AddResourceFragment.$r8$lambda$HTpQYpLtCvgbWda3FPD6sWlnN4Y(Unknown Source:0)
                                                                                                    	at org.ole.planet.myplanet.ui.resources.AddResourceFragment$$ExternalSyntheticLambda7.onClick(D8$$SyntheticClass:0)
                                                                                                    	at android.view.View.performClick(View.java:8028)
                                                                                                    	at android.view.View.performClickInternal(View.java:8005)
                                                                                                    	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
                                                                                                    	at android.view.View$PerformClick.run(View.java:31229)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8705)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

### PR DESCRIPTION
**Pull request by pavi38**
fixes #5702

the app was crashing if the user previously declined the audio permission and than tried to create the audio resource.
Now if the user has denied the permission before, they would be negvigated to the settings where they can change the permissions.

https://github.com/user-attachments/assets/926d01ee-afaa-4158-949f-db652ee1d886

### CODE REVIEW

**Review by Okuro3499 — CHANGES_REQUESTED** [review]
we can keep this dialog to explain to the user why wee need the permission however instead of navigating user to the setting it will be better if you just show the below permission rationale
Screenshot_20250417_142112

Screenshot_20250417_142607

**Comment by pavi38** [comment]
> we can keep this dialog to explain to the user why wee need the permission however instead of navigating user to the setting it will be better if you just show the below permission rationale Screenshot_20250417_142112
> 
> Screenshot_20250417_142607

hi @Okuro3499 it will show the premission rationale if user's permission preference is ask me every time but if their 

> permission rationale

hi @Okuro3499 after android 11 if user has denied the permission on first permission rationale, we can not display the same rationale again. After this scenario they have to manually go into the settings to allow the permission again. Following are few articles that I came across while researching on this topic.



https://stackoverflow.com/questions/67825724/how-to-ask-again-for-permission-if-it-was-denied-in-android
https://developer.android.com/training/permissions/requesting.html#explain

**Comment by pavi38** [comment]
but it will show the permission rationale if the permission are not available and user previously selected ask me every time or just this time.

File: app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceFragment.kt [hunk 1]
```diff
@@ -131,10 +158,30 @@ class AddResourceFragment : BottomSheetDialogFragment() {
 
         createAudioRecorderService(dialog)
         alertSoundRecorderBinding.fabRecord.setOnClickListener {
-            if (!audioRecorderService?.isRecording()!!) {
-                audioRecorderService?.startRecording()
+            if (ContextCompat.checkSelfPermission(requireContext(), Manifest.permission.RECORD_AUDIO)
+                != PackageManager.PERMISSION_GRANTED
+            ) {
+                if (shouldShowRequestPermissionRationale(Manifest.permission.RECORD_AUDIO)) {
```
Comment (pavi38) [inline app/src/main/java/org/ole/planet/myplanet/ui/resources/AddResourceFragment.kt:164]: hi @Okuro3499 I am using the same approach as suggested by chatgpt and I guess microphone is a sensitive permission so always returns false if user denied the permission once.

**Comment by pavi38** [comment]
if (shouldShowRequestPermissionRationale(Manifest.permission.RECORD_AUDIO)) this if statements checks if we are able to show the PermissionRationale if we are not than it show the pop up with link to the settings.

**Comment by pavi38** [comment]
> if (shouldShowRequestPermissionRationale(Manifest.permission.RECORD_AUDIO)) this if statements checks if the system allow us  to show the PermissionRationale. If we are not than it show the pop up with link to the settings.

**Review by Avinash-Codes — APPROVED** [review]

**Review by Okuro3499 — APPROVED** [review]

**Review by dogi — APPROVED** [review]
