### PR TITLE
all: smoother navigation links (fixes #5046)

### LINKED ISSUE #5046: broken navigation links in dashboard
How to reproduce the issue:

1. go to my mylibrary using dashboard.
2. Now try to navigate to mycourses using dashboard.
3. You will see that in the dashboard the mycourses tab is highlighted while you are still in my library

 

https://github.com/user-attachments/assets/c63ed479-0306-423f-b4fb-2cded4a25f17

### PR DESCRIPTION
**Pull request by pavi38**
fixes #5046 

This pull should fix all the broken navigation links in dashboard

https://github.com/user-attachments/assets/b03c9361-e453-482a-97c5-cc2eab301f87

### CODE REVIEW

**Review by Avinash-Codes — CHANGES_REQUESTED** [review]
We have a DashboardActivity.kt.lite file. Please make the intended changes there as well

**Review by deeppp15 — APPROVED** [review]

File: app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt [hunk 1]
```diff
@@ -800,7 +800,9 @@ class DashboardActivity : DashboardElementActivity(), OnHomeItemClickListener, N
         val b = Bundle()
         b.putBoolean("isMyCourseLib", true)
         f.arguments = b
-        openCallFragment(f, "shelf")
+        val fragmentName = f::class.java.simpleName
+        val tag = "My$fragmentName"
```
Comment (Okuro3499) [inline app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt:804]: with this change it means in the DashboardElementActivity this condition will never be true ("shelf" == fragmentTag) you'll need to also update the onBackStackChanged() method to check for the new tag format
```
override fun onBackStackChanged() {
        val f = supportFragmentManager.findFragmentById(R.id.fragment_container)
        val fragmentTag = f?.tag
        Log.d("FragmentTag", "$fragmentTag")
        if (f is CoursesFragment) {
            if ("shelf" == fragmentTag) {
                navigationView.menu.findItem(R.id.menu_mycourses).isChecked = true
            } else {
                navigationView.menu.findItem(R.id.menu_courses).isChecked = true
            }
        } else if (f is ResourcesFragment) {
            if ("shelf" == fragmentTag) {
                navigationView.menu.findItem(R.id.menu_mylibrary).isChecked = true
            } else {
                navigationView.menu.findItem(R.id.menu_library).isChecked = true
            }
        } else if (f is DashboardFragment) {
            navigationView.menu.findItem(R.id.menu_home).isChecked = true
        }
    }
```

**Review by Okuro3499 — CHANGES_REQUESTED** [review]

**Review by Okuro3499 — APPROVED** [review]

**Comment by Okuro3499** [comment]
@Avinash-Codes review this

**Review by Avinash-Codes — APPROVED** [review]

**Review by dogi — APPROVED** [review]
