### PR TITLE
courses: improved stability by filter refactor (fixes #2203)

### LINKED ISSUE #2203: app crash during filter
image

### PR DESCRIPTION
**Pull request by Okuro3499**
fixes #2203
This pull request addresses and resolves the crash that occurs when applying filters within the courses. By identifying and rectifying the underlying cause of the crash, this fix ensures a more stable and reliable user experience during courses filter operations.

### CODE REVIEW

File: app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.java [hunk 1]
```diff
@@ -260,7 +264,15 @@ public ViewHoldercourse(View itemView) {
...
-            itemView.setOnClickListener(view -> openCourse(courseList.get(getAdapterPosition()), 0));
+            itemView.setOnClickListener(v -> {
+                if (adapterPosition != RecyclerView.NO_POSITION) {
+                    openCourse(courseList.get(adapterPosition), 0);
+                }
+            });
+//            itemView.setOnClickListener(view ->
+//                    openCourse(courseList.get(getAdapterPosition()), 0)
+//            );
+
```
Comment (dogi) [inline app/src/main/java/org/ole/planet/myplanet/ui/course/AdapterCourses.java:275]: @Okuro3499 think we should remove this

**Review by dogi — CHANGES_REQUESTED** [review]

**Review by Mutugiii — APPROVED** [review]

**Review by dogi — APPROVED** [review]
