### PR TITLE
all: smoother feedback navigation (fixes #4885)

### LINKED ISSUE #4885: [Bug] Screen replication issue in feedback section
Description:
When navigating to the feedback section, if the feedback icon is pressed multiple times, the app creates multiple instances of the same screen. This causes the user to press the back button multiple times to return to the previous screen.

Steps to Reproduce:

Navigate to the feedback section.
Tap the feedback icon multiple times.
Observe that multiple instances of the screen are added.
Press the back button repeatedly to confirm the issue.
Expected Behavior:
Pressing the feedback icon multiple times should not replicate the screen. Subsequent taps should be ignored if the user is already on the feedback screen.

Actual Behavior:
Multiple instances of the feedback screen are added to the navigation stack.

Screenshots/Video:
 
[Screen_recording_20241217_175135.webm](https://github.com/user-attachments/assets/67b320f4-35ac-4155-a11b-670049ea54d7)

### PR DESCRIPTION
**Pull request by Avinash-Codes**
fixes #4885

### CODE REVIEW

File: app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt [hunk 1]
```diff
@@ -187,25 +189,30 @@ class DashboardActivity : DashboardElementActivity(), OnHomeItemClickListener, N
             when (item.itemId) {
                 R.id.action_chat -> {
                     if (user?.id?.startsWith("guest") == false) {
-                        openCallFragment(ChatHistoryListFragment())
+                        Log.d("openCallFragment", "This is ${ChatHistoryListFragment::class.java.simpleName}")
```
Comment (Okuro3499) [inline app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt:192]: remove logs

**Review by Okuro3499 — CHANGES_REQUESTED** [review]

**Review by Okuro3499 — APPROVED** [review]

**Review by deeppp15 — APPROVED** [review]

**Review by dogi — APPROVED** [review]

**Review by dogi — APPROVED** [review]
