### PR TITLE
Survey data fix (Fixes #1434 ,  Fixes #1435)

### LINKED ISSUE #1434: survey from nation broken
`source` and `parentCode` missing when survey is taken from myPlanet resulting in community not sycning results to planet

Screenshot 2019-12-10 at 6 20 03 PM

### LINKED ISSUE #1435: survey sync from myPlanet replaces all other users data
survey sync from myPlanet replaces all other users data even-though user hasn't used the device, a sync replaces his/ her user data  breaking the other users survey

### PR DESCRIPTION
**Pull request by leomaxi**
https://github.com/open-learning-exchange/myplanet/issues/1434

https://github.com/open-learning-exchange/myplanet/issues/1435

Screenshot 2019-12-10 at 8 58 51 PM

### CODE REVIEW

File: app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java [hunk 1]
```diff
@@ -96,9 +96,11 @@ public void uploadExamResult(final SuccessListener listener) {
         mRealm.executeTransactionAsync(realm -> {
             List<RealmSubmission> submissions = realm.where(RealmSubmission.class).findAll();
             for (RealmSubmission sub : submissions) {
-                try {
-                    RealmSubmission.continueResultUpload(sub, apiInterface, realm,context);
-                } catch (IOException e) {
+               try {
+                   if(sub.getAnswers().size()>0){
```
Comment (rrijal53) [inline app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java]: @leomaxi  if we do this send survey will not work .

Comment (leomaxi) [reply app/src/main/java/org/ole/planet/myplanet/service/UploadManager.java]: Send survey from tablet or from server? This is to prevent overwriting peoples survey data and only sync people the person who used the tablet's data. Issue found was we are overwriting everyone's data including those who didn't use the tablet at all.
